name: Fairy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "v18.14.0"
          cache: "yarn"

      - name: Build
        run: |
          yarn
          yarn build
          yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          // Secrets and variables에서 작성한 PRIVATE KEY이름
          deploy_key: ${{ secrets.GH_PAGES }}
          // next export 실행 후 생성되는 폴더 경로
          publish_dir: ./out 
